[package]
name = "steamworksjs"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.16.8", features = ["tokio_rt", "napi6", "serde-json"] }
napi-derive = "2.16.9"
lazy_static = "1"
tokio = { version = "1", features = ["sync", "time"] }
# WARNING!!! Temp using a specific commit until the PR is merged:
steamworks = { git = "https://github.com/teacher-army/steamworks-rs", rev = "63560b85bfb036bc3f32f2a339b9e6c97ae75d15", features = ["serde"] }
serde = "1"
serde_json = "1"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
