name: Build Only

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    types: [opened, reopened]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc
      - uses: Swatinem/rust-cache@v2
      - name: Node install
        run: npm ci
      - name: Build Windows
        run: npm run build -- --target x86_64-pc-windows-msvc
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-windows
          path: dist
          if-no-files-found: error
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: apt-get update && apt-get install -y curl build-essential
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - name: Node install
        run: npm ci
      - name: Build Linux
        run: npm run build -- --target x86_64-unknown-linux-gnu
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux
          path: dist
          if-no-files-found: error
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-apple-darwin, aarch64-apple-darwin
      - uses: Swatinem/rust-cache@v2
      - name: Node install
        run: npm ci
      - name: Build Mac x64
        run: npm run build -- --target x86_64-apple-darwin
      - name: Build Mac arm64
        run: npm run build -- --target aarch64-apple-darwin
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-macos
          path: dist
          if-no-files-found: error